# Generated by Django 2.1.10 on 2019-10-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20190929_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='app_id',
            field=models.CharField(max_length=21, unique=True),
        ),
    ]
