# Generated by Django 2.1.10 on 2019-10-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20191001_1915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='use_record',
            options={'ordering': ('-used_date',)},
        ),
        migrations.AlterField(
            model_name='use_record',
            name='used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
